# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'taobang.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QWidget,QVBoxLayout, QTableWidgetItem, QTableWidget
import sys



class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(30, 20, 751, 411))
        self.tableWidget.setObjectName("tableWidget")
        # self.tableWidget.setColumnCount(5)
        # self.tableWidget.setRowCount(6)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(300, 460, 211, 41))
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.pushButton.clicked.connect(self.table_analysis)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        
        self.pushButton.setText(_translate("MainWindow", "Tạo bảng"))

    def table_analysis(self):
        self.table = QtWidgets.QTableView(self.tableWidget)
        table_widget = self.tableWidget
        table_widget.setRowCount(5)
        table_widget.setColumnCount(6)
        
# column
        table_widget.setItem(0,0, QTableWidgetItem("Xylanh"))
        table_widget.setItem(0,1, QTableWidgetItem("Pc max"))
        table_widget.setItem(0,2, QTableWidgetItem("P nạp "))
        table_widget.setItem(0,3, QTableWidgetItem("P nạp (lý thuyết)"))
        table_widget.setItem(0,4, QTableWidgetItem("% Chênh lệch"))
        table_widget.setItem(0,5, QTableWidgetItem("Trạng thái"))

# Row
        table_widget.setItem(1,0, QTableWidgetItem("Xylanh 1"))
        table_widget.setItem(2,0, QTableWidgetItem("Xylanh 2"))
        table_widget.setItem(3,0, QTableWidgetItem("Xylanh 3"))
        table_widget.setItem(4,0, QTableWidgetItem("Xylanh 4"))

# Value
        value_1 = 123
        name_1 = "{}".format(value_1)

        value_2 = 234
        name_2 = "{}".format(value_2)

# Add value
        table_widget.setItem(1,1, QTableWidgetItem(name_1))
        table_widget.setItem(2,1, QTableWidgetItem(name_2))



# Display
        # vbox.addWidget(table_widget)
        # self.setLayout(vbox)

        

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
